### ISSUE TITLE
Fix Intel Mac GPT4ALL Install

### ISSUE THREAD

**Issue by mussar0x4D5352** [mussar0x4D5352/honeyBOT#1]
Currently, intel mac has trouble loading version 0.2.3 of the GPT4ALL pip library.

Based on [this issue](https://github.com/nomic-ai/gpt4all/issues/884), there is a separate pathway to install the proper version. Maybe worth hacking into the installer when you get the GPT4ALL model installed during initial setup.

**Comment by AndriyMulyar** [comment]
What is the error you get on the intel mac?
Please try `pip install --upgrade pip` to confirm this error still exists.

**Comment by mussar0x4D5352** [comment]
The error was that version 0.2.3 couldn't be found; validating the pip version looks to have fixed it!
